services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: pcf
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: pcf
    networks:
      - net
networks:
  net: